name: CI
on: [push, pull_request]

jobs:
  build-windows-mingw-inside_msys2_shell:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, msystem_lower: mingw64, arch: x86_64 }
          ,{msystem: MINGW32, msystem_lower: mingw32, arch: i686   }
        ]          
    steps:
      - uses: actions/checkout@v1
        with:
          path: temp
          fetch-depth: 0
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: mingw-w64-${{ matrix.arch }}-toolchain mingw-w64-${{ matrix.arch }}-pkg-config mingw-w64-${{ matrix.arch }}-glfw mingw-w64-${{ matrix.arch }}-ftgl mingw-w64-${{ matrix.arch }}-glew mingw-w64-${{ matrix.arch }}-brotli
          update: true
      - name: Update and Install mingw and packages
        run: |
          msys2 -c 'pacman --noconfirm -Suuy'
          msys2 -c 'pacman --noconfirm -Suu'
      - name: Fix Brotli Bug with static libs
        run: |
          MINGW_ARCH=${{ matrix.msystem }} ./fix_brotli_bug.sh ${{ matrix.msystem_lower }}
        shell: msys2 {0}
# like https://github.com/msys2/MINGW-packages/blob/master/.github/workflows/main.yml#L35
      - name: Move Checkout
        run: |
          Copy-Item -Path "." -Destination "C:\_" -Recurse
      - name: Build
        run: |
          cd /C/_
          MINGW_ARCH=${{ matrix.msystem }} ./made_in_action.sh
        shell: msys2 {0}
        env:
          CC: gcc
          CXX: g++
#      - name: Hmm
#        run: dir C:\_ /S
#        shell: cmd
      - name: Upload build artifacts 1
        uses: actions/upload-artifact@v1
        with:
          name: Package for Debug
          path: C:\_
